# Generated by Django 4.1.7 on 2023-05-28 20:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID Пользователя')),
                ('role', models.IntegerField(choices=[(1, 'Арендатор'), (2, 'Арендодатель'), (3, 'Администратор')], default=1)),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия пользователя')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты пользователя')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона пользователя')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения пользователя')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('rating', models.FloatField(blank=True, default=None, null=True, verbose_name='Рейтинг пользователя')),
                ('avatar', models.UUIDField(blank=True, null=True, verbose_name='ID Аватара пользователя')),
                ('avatar_thumbnail', models.UUIDField(blank=True, null=True, verbose_name='ID Миниатюры аватара пользователя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Пользователь активен?')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Пользователь верифицирован?')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес компании')),
                ('tax_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН')),
                ('logo', models.UUIDField(blank=True, null=True, verbose_name='ID Логотипа компании')),
                ('offer_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='UUID файла с офертой')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='users.user', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['-created_at'],
            },
        ),
    ]
