# Generated by Django 4.1.7 on 2023-05-28 20:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID Метрики')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('method', models.CharField(max_length=255, verbose_name='Метод')),
                ('request_path', models.CharField(max_length=255, verbose_name='Путь')),
                ('status_code', models.IntegerField(verbose_name='Код ответа')),
                ('remote_address', models.CharField(max_length=255, verbose_name='IP адрес')),
                ('taken_time', models.FloatField(verbose_name='Время выполнения запроса')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID Черновика')),
                ('key', models.TextField(verbose_name='Ключ')),
                ('expiration_date', models.DateTimeField(verbose_name='Время истечения срока действия черновика')),
                ('data', models.JSONField(verbose_name='Данные черновика')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Черновик',
                'verbose_name_plural': 'Черновики',
            },
        ),
    ]
